# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main 

strategy:
  matrix:
    py3.9_linux:
      imageName: "ubuntu-latest"
      pythonVersion: 3.9
    py3.10_mac:
      imageName: "macOS-latest"
      pythonVersion: 3.10
    py3.11_windows:
      imageName: "windows-latest"
      pythonVersion: 3.11
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
  displayName: 'Use Python $(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
